workflows:
  version: 2
  main:
    jobs:
      - php56-build

version: 2
jobs:
  php56-build:
    docker:
      - image: circleci/php:5.6
      - image: circleci/mysql:5.7
    environment:
      - WP_TESTS_DIR: "/tmp/wordpress-tests-lib"
      - WP_CORE_DIR: "/tmp/wordpress/"
    steps:
      - checkout
      - run:
          name: "Setup Environment Variables"
          command: |
            echo "export PATH=$HOME/.composer/vendor/bin:$PATH" >> $BASH_ENV
            source /home/circleci/.bashrc
            echo $PATH
      - run:
          name: "Install Dependencies"
          command: |
            sudo apt-get update && sudo apt-get install subversion
            sudo sh -c "printf '\ndeb http://ftp.us.debian.org/debian jessie main\n' >> /etc/apt/sources.list"
            sudo apt-get update && sudo apt-get install mysql-client-5.7
      - run:
          name: "Run Tests"
          command: |
            which mysqladmin
